blank_issues_enabled: false
contact_links:
  - name: ECHO CORP Support & Discussions
    url: https://github.com/mrelive/EC-BlackBox-Viewer/discussions
    about: Ask questions and get support for ECHO CORP Blackbox Viewer
  - name: Original Betaflight Project
    url: https://github.com/betaflight/blackbox-log-viewer
    about: Issues related to the original Betaflight Blackbox Explorer
